### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by nardeas** [BTCP-community/electrumx#4]
Working on a docker image for the server. At a quick glance this should be fairly straightforward to do. Thinking of using alpine linux as base image to keep overhead minimal.

Just have to make sure that zcl daemon compiles successfully. Other than that not expecting big surprises.

**Comment by nardeas** [comment]
Okay there was some problems with alpine libc support as anticipated but seems to be compiling fine now@dolb I think we

**Comment by skinlayers** [comment]
Do we know if musl's dns behavior will have any unforeseen effects?
http://gliderlabs.viewdocs.io/docker-alpine/caveats/

**Comment by nardeas** [comment]
@rizkiwicaksono also made this #5 based on the debian python3.6 image. Also looks pretty good with some minor layer optimization!

**Comment by rizkiwicaksono** [comment]
Is there anything else needed for docker? #5 works perfectly with no compilation error, but surely not the smallest image possible

* Build docker image
```
$ docker build -t electrumx .
Sending build context to Docker daemon  2.255MB
Step 1/23 : FROM python:3.6
 ---> c1e459c00dc3
Step 2/23 : RUN useradd -ms /bin/bash zcluser
 ---> Using cache
 ---> 341d2653290d
[snipped]
Successfully built 5a4f33f0c854
Successfully tagged electrumx:latest
```
* Run docker image
```
$ docker run -it -e RPCUSER=randomuser -e RPCPASS=randompass -p 50002:50002 -t electrumx
Generating RSA private key, 2048 bit long modulus
..+++
...+++
e is 65537 (0x10001)
writing RSA key
Signature ok
subject=/C=NL/CN=electrumx.zclassic.org
Getting Private key
Zcash server starting
INFO:root:ElectrumX server starting
INFO:Controller:event loop policy: None
INFO:Daemon:daemon #1 at 127.0.0.1:8232/ (current)
INFO:BlockProcessor:switching current directory to /home/zcluser/zcl_electrum_db
INFO:BlockProcessor:using leveldb for DB backend
INFO:BlockProcessor:created new database
INFO:BlockProcessor:creating metadata directory
INFO:BlockProcessor:software version: ElectrumX 1.2.1
INFO:BlockProcessor:DB version: 6
```

* Test sending electrum command
```
$ echo '{"params": [], "id": 1, "method": "server.banner"}' | openssl s_client -quiet -connect 127.0.0.1:50002

{"jsonrpc": "2.0", "id": 1, "result": "Welcome to Electrum!"}
```

**Comment by nardeas** [comment]
Indeed. We need further clarifications for the final image

**Comment by dolb** [comment]
As far as I know if should be production ready, so anyone can host a node without any problems. That being said it should be easy to update if the python server needs an urgent update, indexed block chain should be safe as a volume most likely. That being said I wouldn't bother swapping base layer image to anything else - few hundred megabytes makes no difference with several gigs that needs to be downloaded anyway :)

**Comment by nardeas** [comment]
@dolb you're right and more importantly we will most likely face fewer unexpected issues with that base image. For example the alpine is quite hacky with the glibc port and reliability is more important here than space efficiency. I think we should go with the approach in #5

**Comment by rizkiwicaksono** [comment]
I tested my dockerfile on dockerhub with automated build, it runs smoothly, I can spin up droplet instance and run new electrumX within few minutes

https://hub.docker.com/r/rwicaksono/electrumx/

**Comment by rizkiwicaksono** [comment]
there was discussion about where to store zcash params. In my opinion, we need to put it in the docker. We want to avoid any compromise of this key. In docker it was guarded by hashing each layer and version tagging. If it was a separate volume, its possible to run this docker with compromised key.

**Comment by skinlayers** [comment]
I agree, though for other reasons. The zcash params keys are static and always required. If we don't bake them in, they will have to be downloaded when the container is launch, which can take a significant amount of time.

**Comment by ch4ot1c** [comment]
Merged in. Thanks for the discussion!
